#pragma config(Motor,  port1,           frontLeft,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           piston,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           elbow,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           claw,          tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           turnTable,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           backRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          frontRight,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		bLCDBacklight = true;                                    // Turn on LCD Backlight

		string mainBattery;
		string backupBattery;

		//right drive
		/*if (vexRT[Ch2]>10)

		{

			motor[backRight] = 127;
			motor[frontRight] = 127;
		}



		else if (vexRT[Ch2]<-10)

		{

			motor[backRight] = -127;
			motor[frontRight] = -127;

		}

		else

		{

			motor[backRight] = 0;
			motor[frontRight] = 0;

		}
		//left drive
		if (vexRT[Ch3]>10)

		{

			motor [backLeft] = 127;
			motor [frontLeft] = 127;

		}



		else if (vexRT[Ch3]<-10)

		{

			motor[backLeft] = -127;
			motor[frontLeft] = -127;

		}

		else

		{

			motor[backLeft] = 0;
			motor[frontLeft] = 0;

		}
		*/

		motor[frontRight] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
    motor[backRight] =  vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
    motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
    motor[backLeft] =  vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];

//claw
		if(vexRT[Btn8U] == 1)
		{
			motor[claw] = 127;
		}
		else if(vexRT[Btn8D] == 1)
		{
			motor[claw] = -127;
		}
		else
		{
			motor[claw] = 0;
		}
//turntable

		if(vexRT[Btn8L] == 1)
		{
			motor[turnTable] = 127;
		}
		else if(vexRT[Btn8R] == 1)
		{
			motor[turnTable] = -127;
		}
		else
		{
			motor[turnTable] = 0;
		}
//intake


		if(vexRT[Btn7L] == 1)
		{
			motor[intake] = 127;
		}
		else if(vexRT[Btn7R] == 1)
		{
			motor[intake] = -127;
		}
		else
		{
			motor[intake] = 0;
		}

//lift
		if(vexRT[Btn6U] == 1)
		{
			motor[lift] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[lift] = -127;
		}
		else
		{
			motor[lift] = 0;
		}
				//piston
		if(vexRT[Btn5D] == 1)
		{
			motor[piston] = 127;
		}
		else if(vexRT[Btn5U] == 1)
		{
			motor[piston] = -127;
		}
		else
		{
			motor[piston] = 0;
		}
	//elbow
			if(vexRT[Btn7D] == 1)
		{
			motor[elbow] = 127;
		}
		else if(vexRT[Btn7U] == 1)
		{
			motor[elbow] = -127;
		}
		else
		{
			motor[elbow] = 0;
		}

		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD

		//clearLCDLine(1);                                            // Clear line 2 (1) of the LCD



		//Display the Primary Robot battery voltage

		displayLCDString(0, 0, "Primary: ");

		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed

		displayNextLCDString(mainBattery);



		//Display the Backup battery voltage

		displayLCDString(1, 0, "Backup: ");

		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed

		displayNextLCDString(backupBattery);



		//Short delay for the LCD refresh rate



		//center wheel
		/*
		if	((vexRT[Ch3]>10) && (vexRT[Ch2]<-10))
		{
		motor[center] = 0;
		}

		else if ((vexRT[Ch3]<-10) && (vexRT[Ch2]>10))
		{
		motor[center] = 0;
		}

		else if (vexRT[Ch2]>10)
		{
		motor[center] = 127;
		}
		else if (vexRT[Ch2]<-10)
		{
		motor[center] = -127;
		}
		else
		{
		motor[center] = 0;
		}
		*/



	}

}
