#pragma config(Motor,  port2,           motorOne,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motorTwo,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           motorThree,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           motorFour,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{

	//forward/backward
	motor[motorOne] = vexRT[Ch3] ;
	motor[motorTwo] = vexRT[Ch3] ;
	motor[motorThree] = vexRT[Ch3] ;
	motor[motorFour] = vexRT[Ch3] ;
	//turn
	motor[motorOne] = vexRT[Ch1]  ;
	motor[motorTwo] = vexRT[Ch1] * -1;
	motor[motorThree] = vexRT[Ch1] * -1;
	motor[motorFour] = vexRT[Ch1] ;

		//strafe left
	if(vexRT[Btn7L] == 1)
	{
motor[motorTwo] = 127;
motor[motorThree] = -127;
motor[motorOne] = 127;
motor[motorFour] = -127;
}
else if(vexRT[Btn7R] ==1)
{
motor[motorTwo] = -127;
motor[motorThree] = 127;
motor[motorOne] = -127;
motor[motorFour] = 127;
}
}
}
