#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           arms,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           claw,          tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		if(abs(vexRT[Ch2])>5)
		{
			motor[backLeft] = vexRT[Ch2]*1;
			motor[frontLeft] = vexRT[Ch2]*1;
		}

		if(abs(vexRT[Ch1])>5)
		{
			motor[backLeft] = vexRT[Ch1]*-1;
			motor[frontLeft] = vexRT[Ch1]*1;
		}

		if(abs(vexRT[Ch3])>5)
		{
			motor[backRight] = vexRT[Ch3]*1;
			motor[frontRight] = vexRT[Ch3]*1;
		}

		if(abs(vexRT[Ch4])>5)
		{
			motor[backRight] = vexRT[Ch4]*1;
			motor[frontRight] = vexRT[Ch4]*-1;
		}

		if (vexRT [Btn5D] == 1)
		{
			motor [frontLeft] = 0;
			motor [frontRight] = 0;
			motor [backLeft] = 0;
			motor [backRight] = 0;
			motor [arms] = 0;
			motor [claw] = 0;
		}

		if (vexRT[Btn6D] == 1)
		{
			motor [arms] = 127;
		}
		else if (vexRT [Btn6U] == 1)
		{
			motor [arms] = -127;
		}
		else (vexRT[Btn6D] == 0);
		{
			motor [arms] = 0;
		}


		//this was co-programmed by Vaishnavi
		//so that each channel can do many things
		//thanks!


		if (vexRT[Btn8U] == 1)
		{
			motor [claw] = 127;
		}
		else if (vexRT [Btn8D] == 1)
		{
			motor [claw] = -127;
		}
		else
		{
			motor [claw] = 0;
		}

	}

}
