#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  InputUltra,     sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_7,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           mobileLift,    tmotorNone, openLoop)
#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, PIDControl, reversed, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, PIDControl, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, PIDControl, driveRight, encoderPort, I2C_3)
#pragma config(Motor,  port5,           frontLeft,     tmotorVex393_MC29, PIDControl, reversed, driveLeft, encoderPort, I2C_4)
#pragma config(Motor,  port6,           arms1,         tmotorVex393_MC29, PIDControl, encoderPort, I2C_5)
#pragma config(Motor,  port7,           claw,          tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_6)
#pragma config(Motor,  port8,           arms2,         tmotorVex393_MC29, PIDControl, encoderPort, I2C_7)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main ()
{
	{bLCDBacklight = true;                                    // Turn on LCD Backlight
		string mainBattery;//, backupBattery;
while (true)
{
		slaveMotor(arms1, arms2);

		resetMotorEncoder(backLeft);
		resetMotorEncoder(frontLeft);
		resetMotorEncoder(backRight);
		resetMotorEncoder(frontRight);
		resetMotorEncoder(claw);
		resetMotorEncoder(arms1);

		if(vexRT[Ch3]>10)

		{
			motor[backLeft] = 127;
			motor[frontLeft] = 127;
		}

		else if (vexRT[Ch3]<-10)
		{
			motor[backLeft] = -127;
			motor[frontLeft] = -127;
		}
		else
		{
			motor[backLeft] = 0;
			motor[frontLeft] = 0;
		}

		if (vexRT[Ch2]>10)
		{
			motor [backRight] = 127;
			motor [frontRight] = 127;
		}

		else if (vexRT[Ch2]<-10)
		{
			motor[backRight] = -127;
			motor[frontRight] = -127;
		}
		else
		{
			motor[backRight] = 0;
			motor[frontRight] = 0;
		}

		if (vexRT[Btn5D] == 1)
		{
			motor [frontLeft] = 0;
			motor [frontRight] = 0;
			motor [backLeft] = 0;
			motor [backRight] = 0;
			motor [arms1] = 0;
			motor [claw] = 0;
		}

		if (vexRT[Btn7R] == 1)
		{
		motor [mobileLift] = 127;
		}
		else if (vexRT[Btn7L] == 1)
		{
		motor [mobileLift] = -127;
		}
		else
		{
		motor [mobileLift] = 0;
		}

		if (vexRT[Btn8U] == 1)
		{
			motor [claw] = 127;
		}
		else if (vexRT [Btn8D] == 1)
		{
			motor [claw] = -127;
		}
		else
		{
			motor [claw] = 0;
		}


		if (vexRT[Btn6D] == 1)
		{
			motor [arms1] = 127;
			wait1Msec(1200);
		}
		else if (vexRT [Btn6U] == 1)
		{
			motor [arms1] = -127;
			//wait1Msec(500);
		//	motor [arms1] = 0;
		}
		else
		{
			motor [arms1] = 0;
		}


		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		//clearLCDLine(1);                                            // Clear line 2 (1) of the LCD

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		//displayLCDString(1, 0, "Backup: ");
		//sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed
		//displayNextLCDString(backupBattery);

		//Short delay for the LCD refresh rate
		wait1Msec(10);
	}
}
}
